### ISSUE TITLE
Unable to run the prose mirror demo (typescript) latest source code

### ISSUE THREAD

**Issue by rajeshkdev** [ProseMirror/prosemirror#1279]
@marijnh, I'm unable to run the Demo.  Took the latest via Git Clone 
Tried to setup the Typescript version of [prose mirror](https://github.com/ProseMirror/prosemirror).  

Some how the `package.json` missed out the demo script, I have added the following

```
"scripts": {
    "test": "bin/pm test",
    "demo": "esmoduleserve demo/ --port 8080"
  },
```

After the `npm run demo` command, Got the following exception:

```
Uncaught TypeError: Failed to resolve module specifier "prosemirror-model". 
Relative references must start with either "/", "./", or "../".
```
Also I see many error after taking the source code latest version. During `bin/pm build` command execution

```
Found 42 errors. Watching for file changes.
'prosemirror-model' is imported by commands/src/commands.d.ts, 
but could not be resolved – treating it as an external dependency
```

Another error:

```
inputrules/src/inputrules.ts(70,7): error TS2322: Type 'Plugin<null>' is not assignable to type 'Plugin<{ transform: Transaction; from: number; to: number; text: string; } | null>'.
The types of 'spec.state' are incompatible between these types.
```

Request you to suggest.

**Comment by marijnh** [comment]
The readme was out of date. Patch ead01b1 updates it.

So on a fresh clone of this repository, on Linux, running `bin/pm install` fails? Which npm and node version are you using?

**Comment by rajeshkdev** [comment]
You are awesome @marijnh, Thank you for the understanding! :)

The fresh clone of this repository is working well, but the compilation fails while running the `bin/pm dev-start` OR `bin/pm build`

I'm using the following version of npm and node. Could you please suggest if anything needs to be upgraded or downgraded?

```
~/EditorNextGen/prosemirror$ npm --version
6.14.17
~/EditorNextGen/prosemirror$ node --version
v14.19.2
```

Also I noticed the `bin/pm test` fails with following error:

```
~/EditorNextGen/prosemirror$ bin/pm test
(node:6493) UnhandledPromiseRejectionWarning: Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'prosemirror-test-builder' imported from /home/rajeshkumar/EditorNextGen/prosemirror/model/test/test-content.js
    at new NodeError (internal/errors.js:322:7)
    at packageResolve (internal/modules/esm/resolve.js:732:9)
    at moduleResolve (internal/modules/esm/resolve.js:773:18)
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:887:11)
    at Loader.resolve (internal/modules/esm/loader.js:89:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:242:28)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:76:40)
    at link (internal/modules/esm/module_job.js:75:36)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:6493) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:6493) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by marijnh** [comment]
Did your patch to tsconfig solve this?

**Comment by rajeshkdev** [comment]
No it didn't solve it completely, But It has fixed few compilation issues. 
I have resolved all the compilation issues, However I have observed a strange behavior, So I'm not sure I have done it well

Since my clone is fresh, the project `node_modules` doesn't contain package references for each submodules.
Each submodule is referring to specific version of prose mirror instead of the local submodules (previously JS version of prose mirror was pointing to local submodules- and my changes reflects immediately)

**For ex:**  
`model/schema.ts` is using `import OrderedMap from "orderedmap"`
`demo/demo.ts` is using `import {EditorState} from "prosemirror-state"` and `import {schema} from "prosemirror-schema-basic"`

These packages were not part of node_modules, so I have added them in package.json as dev dependencies (I guess this is not proper way to do it)

```
"devDependencies": {
    "crelt": "^1.0.5",
    "orderedmap": "^1.1.8",
    "prosemirror-example-setup": "^1.2.0",
    "prosemirror-inputrules": "^1.2.0",
    "prosemirror-menu": "^1.2.0",
    "prosemirror-model": "^1.17.0",
    "prosemirror-schema-basic": "^1.2.0",
    "prosemirror-schema-list": "^1.2.0",
    "prosemirror-view": "^1.25.0",
    "rope-sequence": "^1.3.3",
    "w3c-keyname": "^2.2.4"
  }
```

After doing above step I was able to run the demo version of Prose mirror dev (Typescript), however my changes are not coming in the browser its due to the dependencies referring to `node_modules ` and not local submodules.
If I remove the dev dependencies from `node_modules` the compilation issues preventing the successful demo run.

Please suggest

**Comment by marijnh** [comment]
> Since my clone is fresh, the project node_modules doesn't contain package references for each submodules.

So, again, which npm version are you using?

**Comment by rajeshkdev** [comment]
> > Since my clone is fresh, the project node_modules doesn't contain package references for each submodules.
> 
> So, again, which npm version are you using?

The same version I'm using as previous
```
~/EditorNextGen/prosemirror$ npm --version
6.14.17
~/EditorNextGen/prosemirror$ node --version
v14.19.2

Do you want me to try downgrade Or upgrade? 
Could you Please share the version details that you're using.... 
```

**Comment by marijnh** [comment]
Try upgrading to node 16 / npm 8. I think your version doesn't support workspaces yet (which is the feature that links the repositories together).

**Comment by rajeshkdev** [comment]
Great! Its working now, the changes are also reflecting without any issues! :)

Thanks a lot for the response and phenomenal prose mirror framework!!

**Comment by eyebrowkang** [comment]
Hello, have the same problem, but the build is no error, and I tried the things above, still not works.

Detail info here: 
```
π prosemirror master ✗ ❯ bin/pm install
Skipping cloning of model (directory exists)
Skipping cloning of transform (directory exists)
Skipping cloning of state (directory exists)
Skipping cloning of view (directory exists)
Skipping cloning of keymap (directory exists)
Skipping cloning of inputrules (directory exists)
Skipping cloning of history (directory exists)
Skipping cloning of collab (directory exists)
Skipping cloning of commands (directory exists)
Skipping cloning of gapcursor (directory exists)
Skipping cloning of schema-basic (directory exists)
Skipping cloning of schema-list (directory exists)
Skipping cloning of menu (directory exists)
Skipping cloning of example-setup (directory exists)
Skipping cloning of markdown (directory exists)
Skipping cloning of dropcursor (directory exists)
Skipping cloning of test-builder (directory exists)
Skipping cloning of changeset (directory exists)
Skipping cloning of website (directory exists)
Running npm install
Building modules
Building...
Done in 6.44s
 π prosemirror master ✗ ❯ bin/pm build
Building...
Done in 6.27s
 π prosemirror master ✗ ❯ bin/pm dev-start
Dev server listening on 8080
Starting compilation in watch mode...
inputrules/src/inputrules.ts(70,7): error TS2322: Type 'Plugin<null>' is not assignable to type 'Plugin<{ transform: Transaction; from: number; to: number; text: string; } | null>'.
  The types of 'spec.props' are incompatible between these types.
    Type 'EditorProps<Plugin<null>> | undefined' is not assignable to type 'EditorProps<Plugin<{ transform: Transaction; from: number; to: number; text: string; } | null>> | undefined'.
      Type 'EditorProps<Plugin<null>>' is not assignable to type 'EditorProps<Plugin<{ transform: Transaction; from: number; to: number; text: string; } | null>>'.
        Type 'Plugin<{ transform: Transaction; from: number; to: number; text: string; } | null>' is not assignable to type 'Plugin<null>'.
          The types of 'spec.state' are incompatible between these types.
            Type 'StateField<{ transform: Transaction; from: number; to: number; text: string; } | null> | undefined' is not assignable to type 'StateField<null> | undefined'.
              Type 'StateField<{ transform: Transaction; from: number; to: number; text: string; } | null>' is not assignable to type 'StateField<null>'.
                The types returned by 'init(...)' are incompatible between these types.
                  Type '{ transform: Transaction; from: number; to: number; text: string; } | null' is not assignable to type 'null'.
                    Type '{ transform: Transaction; from: number; to: number; text: string; }' is not assignable to type 'null'.

markdown/src/from_markdown.ts(3,8): error TS1259: Module '"/Users/eyebrow/clone/prosemirror/node_modules/@types/markdown-it/lib/token"' can only be default-imported using the 'allowSyntheticDefaultImports' flag

Found 2 errors. Watching for file changes.
Bundling model, transform, state, view, keymap, inputrules, history, collab, commands, gapcursor, schema-basic, schema-list, menu, example-setup, markdown, dropcursor, test-builder, changeset
Bundling done.
^CStop
Stop
 π prosemirror master ✗ ❯ node -v
v16.20.1
 π prosemirror master ✗ ❯ npm -v
8.19.4
 π prosemirror master ✗ ❯ tsc -v
Version 4.9.5

```

**Comment by eyebrowkang** [comment]
It works now, thanks.

And sorry about commenting under this closed issue, It's my bad
