### ISSUE TITLE
TypeError updateStateInner(prosemirror-view/dist/index)

### ISSUE THREAD

**Issue by rfgamaral** [ProseMirror/prosemirror#1333]
Hi there,

We've noticed some Sentry events for one particular error: `Cannot read properties of null (reading 'matchesNode')`. It doesn't seem to be causing any issues on our side, we haven't noticed anything crashing, nor we had any support tickets coming in related to this, but I thought I'd just mention it here anyway.

Maybe this could be easily prevented with `this.docView?.matchesNode`?

```
TypeError: Cannot read properties of null (reading 'matchesNode')
  at updateStateInner(./node_modules/prosemirror-view/dist/index.js:5012:49)
  at updateState(./node_modules/prosemirror-view/dist/index.js:4985:14)
  at call(./node_modules/@tiptap/core/dist/tiptap-core.esm.js:3541:19)
  at dispatch(./node_modules/prosemirror-view/dist/index.js:5300:33)
  at exitCode(./node_modules/@tiptap/core/dist/tiptap-core.esm.js:64:26)
  at method(./node_modules/@tiptap/core/dist/tiptap-core.esm.js:3114:53)
  at direct(./node_modules/@tiptap/core/dist/tiptap-core.esm.js:1058:45)
  at f(./node_modules/prosemirror-keymap/dist/index.js:100:23)
  at f(./node_modules/prosemirror-view/dist/index.js:2901:50)
  at someProp(./node_modules/prosemirror-view/dist/index.js:5122:50)
  at handler(./node_modules/prosemirror-view/dist/index.js:2901:19)
  at apply(./node_modules/prosemirror-view/dist/index.js:2823:17)
  at HTMLDivElement.i(./node_modules/@sentry/browser/esm/helpers.js:74:23)
```

![image](https://user-images.githubusercontent.com/96476/201890589-72fa70f1-d196-43f5-a5d6-453926b3a950.png)

**Comment by marijnh** [comment]
This will happen if you try to dispatch updates to an editor after you have destroyed it. I'd consider that an error in your code. You can use `view.isDestroyed` to check for this if necessary.
