### ISSUE TITLE
Duplicate definition of command [object Object]:undefined

### ISSUE THREAD

**Issue by sielay** [ProseMirror/prosemirror#153]
Master HEAD, basic setup like in demos.

```
Error: Duplicate definition of command [object Object]:undefined
    at AssertionError.Error (native)
    at AssertionError.ProseMirrorError (...prosemirror/src/util/sortedinsert.js:30440:90)
    at new AssertionError (...prosemirror/src/util/sortedinsert.js:30478:83)
    at Function.raise (...prosemirror/src/util/sortedinsert.js:30463:13)
    at add (...prosemirror/src/util/sortedinsert.js:19095:55)
    at ...prosemirror/src/util/sortedinsert.js:19102:13
    at Schema.registry (...prosemirror/src/util/sortedinsert.js:13288:15)
    at CommandSet.op (...prosemirror/src/util/sortedinsert.js:19101:18)
    at CommandSet.derive (...prosemirror/src/util/sortedinsert.js:19140:12)
    at CommandSet.derive (...prosemirror/src/util/sortedinsert.js:19139:44)
    at Option.updateCommands [as update] (...prosemirror/src/util/sortedinsert.js:19291:21)
    at initOptions (...prosemirror/src/util/sortedinsert.js:21786:48)
    at new ProseMirror (...prosemirror/src/util/sortedinsert.js:21025:30)
    at ...prosemirror/src/util/sortedinsert.js:173:8
From previous event:
    at Object.3.../../shared/content-blocks (...prosemirror/src/util/sortedinsert.js:167:36)
    at s (...prosemirror/src/util/sortedinsert.js:1:254)
    at e (...prosemirror/src/util/sortedinsert.js:1:425)
    at ...prosemirror/src/util/sortedinsert.js:1:443
```

**Comment by marijnh** [comment]
If you don't show the code that causes this, I can't tell you what you're doing wrong.

**Comment by sielay** [comment]
Ignore. Found it. I one example with `/src`and one with `/dist`. For future, especially it's distributed as node_module it would be worth to describe main in package.json to target dist so you don't have to import like `prosemirror/dist/*` but just `prosemirror/*`

**Comment by marijnh** [comment]
Agreed, I did that last week in 9614fc22
