### ISSUE TITLE
npm install fails on OSX

### ISSUE THREAD

**Issue by friksa** [ProseMirror/prosemirror#334]
Did a git clone on OSX 10.11.4 (with all software updates) and node 5.10.1, npm 3.8.9 and node-gyp 3.3.1

It fails complaining about not find package fuse.  Even npm -g install fuse does not make a difference.

````
npm install
npm WARN prefer global node-gyp@3.3.1 should be installed with -g

> fuse-bindings@2.8.1 install /Users/fstrecker/dev-sp/prosemirror/node_modules/fuse-bindings
> prebuild --install

prebuild WARN install Prebuilt binaries for node version v5.10.1 are not available
Package fuse was not found in the pkg-config search path.
Perhaps you should add the directory containing `fuse.pc'
to the PKG_CONFIG_PATH environment variable
No package 'fuse' found
gyp: Call to 'pkg-config fuse --cflags-only-I | sed s/-I//g' returned exit status 0 while in binding.gyp. while trying to load binding.gyp
prebuild ERR! configure error 
prebuild ERR! stack Error: `gyp` failed with exit code: 1
prebuild ERR! stack     at ChildProcess.onCpExit (/Users/fstrecker/dev-sp/prosemirror/node_modules/node-gyp/lib/configure.js:305:16)
prebuild ERR! stack     at emitTwo (events.js:100:13)
prebuild ERR! stack     at ChildProcess.emit (events.js:185:7)
prebuild ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
prebuild ERR! not ok 
prebuild ERR! build Error: `gyp` failed with exit code: 1
prebuild ERR! build     at ChildProcess.onCpExit (/Users/fstrecker/dev-sp/prosemirror/node_modules/node-gyp/lib/configure.js:305:16)
prebuild ERR! build     at emitTwo (events.js:100:13)
prebuild ERR! build     at ChildProcess.emit (events.js:185:7)
prebuild ERR! build     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
npm WARN install:fuse-bindings@2.8.1 fuse-bindings@2.8.1 install: `prebuild --install`
npm WARN install:fuse-bindings@2.8.1 Exit status 2

> prosemirror@0.6.1 prepublish /Users/fstrecker/dev-sp/prosemirror
> rimraf dist && babel -d dist src

module.js:341
    throw err;
    ^

Error: Cannot find module 'brace-expansion'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/fstrecker/dev-sp/prosemirror/node_modules/minimatch/minimatch.js:10:14)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)

npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v5.10.1
npm ERR! npm  v3.8.9
npm ERR! code ELIFECYCLE
npm ERR! prosemirror@0.6.1 prepublish: `rimraf dist && babel -d dist src`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the prosemirror@0.6.1 prepublish script 'rimraf dist && babel -d dist src'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the prosemirror package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     rimraf dist && babel -d dist src
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs prosemirror
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls prosemirror
npm ERR! There is likely additional logging output above.
````

**Comment by marijnh** [comment]
The fuse-bindings dependency is optional (in `distfs`), which I assume is the reason you only get a warning, not an error. But then, it appears that you _do_ have missing non-optional dependencies after npm finishes installing, which is very odd.

`brace-expansion` is both a dependency of `fuse-bindings` (optional dependency) and `minimatch` (non-optional dependency via babel). This might be an NPM bug where in such a case it'll fail to install it, even though it should.

Do you want to further test and report this to the NPM people?

**Comment by friksa** [comment]
Definitely want to resolve it, but need ideas on what to try next.  Thanks!

**Comment by marijnh** [comment]
If you just want to get past this, do `npm install brace-expansion` and you should be good to do.

If you want to help get this NPM bug fixed, create a dummy project with `fuse-bindings` as optional dependency and `minimatch` as non-optional dependency, and see if installing it causes `brace-expansion` to be installed (even though `fuse-bindings` will fail). If not, submit that as a failing test case on the NPM bug tracker.

**Comment by friksa** [comment]
No luck with getting it to work
````
$ sudo npm -g install brace-expansion
/usr/local/lib
`-- brace-expansion@1.1.4 

$ sudo npm -g install fuse
/usr/local/bin/fuse -> /usr/local/lib/node_modules/fuse/bin/fuse.js
/usr/local/lib
`-- fuse@0.4.0 

$ npm install
npm WARN prefer global node-gyp@3.3.1 should be installed with -g

> fuse-bindings@2.8.1 install /Users/fstrecker/dev-sp/prosemirror/node_modules/fuse-bindings
> prebuild --install

prebuild WARN install Prebuilt binaries for node version v5.10.1 are not available
Package fuse was not found in the pkg-config search path.
Perhaps you should add the directory containing `fuse.pc'
to the PKG_CONFIG_PATH environment variable
No package 'fuse' found
gyp: Call to 'pkg-config fuse --cflags-only-I | sed s/-I//g' returned exit status 0 while in binding.gyp. while trying to load binding.gyp
prebuild ERR! configure error 
prebuild ERR! stack Error: `gyp` failed with exit code: 1
prebuild ERR! stack     at ChildProcess.onCpExit (/Users/fstrecker/dev-sp/prosemirror/node_modules/node-gyp/lib/configure.js:305:16)
prebuild ERR! stack     at emitTwo (events.js:100:13)
prebuild ERR! stack     at ChildProcess.emit (events.js:185:7)
prebuild ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
prebuild ERR! not ok 
prebuild ERR! build Error: `gyp` failed with exit code: 1
prebuild ERR! build     at ChildProcess.onCpExit (/Users/fstrecker/dev-sp/prosemirror/node_modules/node-gyp/lib/configure.js:305:16)
prebuild ERR! build     at emitTwo (events.js:100:13)
prebuild ERR! build     at ChildProcess.emit (events.js:185:7)
prebuild ERR! build     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
npm WARN install:fuse-bindings@2.8.1 fuse-bindings@2.8.1 install: `prebuild --install`
npm WARN install:fuse-bindings@2.8.1 Exit status 2

> prosemirror@0.6.1 prepublish /Users/fstrecker/dev-sp/prosemirror
> rimraf dist && babel -d dist src

module.js:341
    throw err;
    ^

Error: Cannot find module 'inflight'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/fstrecker/dev-sp/prosemirror/node_modules/rimraf/node_modules/glob/glob.js:57:16)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)

npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v5.10.1
npm ERR! npm  v3.8.9
npm ERR! code ELIFECYCLE
npm ERR! prosemirror@0.6.1 prepublish: `rimraf dist && babel -d dist src`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the prosemirror@0.6.1 prepublish script 'rimraf dist && babel -d dist src'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the prosemirror package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     rimraf dist && babel -d dist src
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs prosemirror
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls prosemirror
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/fstrecker/dev-sp/prosemirror/npm-debug.log

````

**Comment by friksa** [comment]
I really only need a distribution version of the project.  We want to start integrating ProseMirror into a project.  Is there a place where we can download a compiled version of the latest version since we are not able to compile it?

Thanks!

**Comment by marijnh** [comment]
NPM is where you can get compiled versions.

You don't need fuse for anything. If you just keep installing the missing packages (in this case, `inflight`), you should get a working install pretty quickly.

**Comment by friksa** [comment]
No luck :(
````
$ sudo npm -g install inflight
/usr/local/lib
`-- inflight@1.0.4 

$ npm install
npm WARN prefer global node-gyp@3.3.1 should be installed with -g

> fuse-bindings@2.8.1 install /Users/fstrecker/dev-sp/prosemirror/node_modules/fuse-bindings
> prebuild --install

prebuild WARN install Prebuilt binaries for node version v5.10.1 are not available
Package fuse was not found in the pkg-config search path.
Perhaps you should add the directory containing `fuse.pc'
to the PKG_CONFIG_PATH environment variable
No package 'fuse' found
gyp: Call to 'pkg-config fuse --cflags-only-I | sed s/-I//g' returned exit status 0 while in binding.gyp. while trying to load binding.gyp
prebuild ERR! configure error 
prebuild ERR! stack Error: `gyp` failed with exit code: 1
prebuild ERR! stack     at ChildProcess.onCpExit (/Users/fstrecker/dev-sp/prosemirror/node_modules/node-gyp/lib/configure.js:305:16)
prebuild ERR! stack     at emitTwo (events.js:100:13)
prebuild ERR! stack     at ChildProcess.emit (events.js:185:7)
prebuild ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
prebuild ERR! not ok 
prebuild ERR! build Error: `gyp` failed with exit code: 1
prebuild ERR! build     at ChildProcess.onCpExit (/Users/fstrecker/dev-sp/prosemirror/node_modules/node-gyp/lib/configure.js:305:16)
prebuild ERR! build     at emitTwo (events.js:100:13)
prebuild ERR! build     at ChildProcess.emit (events.js:185:7)
prebuild ERR! build     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
npm WARN install:fuse-bindings@2.8.1 fuse-bindings@2.8.1 install: `prebuild --install`
npm WARN install:fuse-bindings@2.8.1 Exit status 2

> prosemirror@0.6.1 prepublish /Users/fstrecker/dev-sp/prosemirror
> rimraf dist && babel -d dist src

module.js:341
    throw err;
    ^

Error: Cannot find module 'inflight'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/fstrecker/dev-sp/prosemirror/node_modules/rimraf/node_modules/glob/glob.js:57:16)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)

npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v5.10.1
npm ERR! npm  v3.8.9
npm ERR! code ELIFECYCLE
npm ERR! prosemirror@0.6.1 prepublish: `rimraf dist && babel -d dist src`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the prosemirror@0.6.1 prepublish script 'rimraf dist && babel -d dist src'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the prosemirror package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     rimraf dist && babel -d dist src
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs prosemirror
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls prosemirror
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/fstrecker/dev-sp/prosemirror/npm-debug.log
````

**Comment by marijnh** [comment]
You shouldn't be installing this stuff globally. But I can't explain how that library is missing right after you install it. Note that you don't have to keep running `npm install` in the prosemirror directory -- that's just going to keep failing in the same way.

What's your NPM version? Maybe see if upgrading helps.

**Comment by friksa** [comment]
Ok, I installed prosemirror sing npm...

The dist folder does not contain bundle_basic.js used in your basic demo on the web site. It contains main separate js files.  Where do I start to get a basic production version of the client going?  (I understand it is still in beta).

**Comment by marijnh** [comment]
The demos are in the [website](https://github.com/ProseMirror/website) repository, which has its own build scripts.

**Comment by friksa** [comment]
I have the latest version of npm:
node 5.10.1, npm 3.8.9 and node-gyp 3.3.1

**Comment by friksa** [comment]
Got it working after installing Fuse from:
https://osxfuse.github.io
