### ISSUE TITLE
npm install fails on Ubuntu 16.04.1

### ISSUE THREAD

**Issue by hyperkun** [ProseMirror/prosemirror#494]
I can't install ProseMirror from master branch. My NodeJS is v.4.2.6, and NPM is v.3.5.2.
Here's the output of ```npm install```:
```
$ npm install
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

> prosemirror@0.0.0 install /home/andy/prosemirror
> bin/pm clone

/home/andy/prosemirror/bin/pm.js:13
let origDir = process.cwd()
^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3

npm ERR! Linux 4.4.0-45-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! prosemirror@0.0.0 install: `bin/pm clone`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the prosemirror@0.0.0 install script 'bin/pm clone'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the prosemirror package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     bin/pm clone
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs prosemirror
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls prosemirror
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/andy/prosemirror/npm-debug.log
```

**Comment by marijnh** [comment]
Upgrade to node 6.x. Or, if you just want to use ProseMirror as a library, install the individual packages from NPM rather than cloning the prosemirror repository.
