### ISSUE TITLE
error occur when use webpack to package the project

### ISSUE THREAD

**Issue by CooCooooo** [ProseMirror/prosemirror#65]
Hash: a7e67fc458a9cba10338
Version: webpack 1.12.2
Time: 18050ms
    Asset    Size  Chunks             Chunk Names
bundle.js  226 kB       0  [emitted]  main
    + 50 hidden modules

ERROR in ./src/edit/commands.js
Module build failed: Error: C:/Users/zhou/Desktop/prosemirror/src/edit/commands.js: We found a path that isn't a NodePath instance
    at Function.get (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-preset-es2015\node_modules\babel-plugin-transform-es2015-block-scoping\node_modules\babel-traverse\lib\path\index.js:103:13)
    at TraversalContext.create (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-preset-es2015\node_modules\babel-plugin-transform-es2015-block-scoping\node_modules\babel-traverse\lib\context.js:73:30)
    at TraversalContext.visitMultiple (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-preset-es2015\node_modules\babel-plugin-transform-es2015-block-scoping\node_modules\babel-traverse\lib\context.js:102:25)
    at TraversalContext.visit (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-preset-es2015\node_modules\babel-plugin-transform-es2015-block-scoping\node_modules\babel-traverse\lib\context.js:193:19)
    at Function.traverse.node (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-preset-es2015\node_modules\babel-plugin-transform-es2015-block-scoping\node_modules\babel-traverse\lib\index.js:139:17)
    at traverse (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-preset-es2015\node_modules\babel-plugin-transform-es2015-block-scoping\node_modules\babel-traverse\lib\index.js:61:12)
    at Function.traverse.hasType (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-preset-es2015\node_modules\babel-plugin-transform-es2015-block-scoping\node_modules\babel-traverse\lib\index.js:188:3)
    at BlockScoping.wrapClosure (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-preset-es2015\node_modules\babel-plugin-transform-es2015-block-scoping\lib\index.js:491:47)
    at BlockScoping.run (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-preset-es2015\node_modules\babel-plugin-transform-es2015-block-scoping\lib\index.js:383:12)
    at PluginPass.Loop (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-preset-es2015\node_modules\babel-plugin-transform-es2015-block-scoping\lib\index.js:89:36)
    at newFn (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-core\node_modules\babel-traverse\lib\visitors.js:233:27)
    at NodePath._call (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-core\node_modules\babel-traverse\lib\path\context.js:72:18)
    at NodePath.call (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-core\node_modules\babel-traverse\lib\path\context.js:44:17)
    at NodePath.visit (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-core\node_modules\babel-traverse\lib\path\context.js:102:12)
    at TraversalContext.visitQueue (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-core\node_modules\babel-traverse\lib\context.js:151:16)
    at TraversalContext.visitMultiple (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-core\node_modules\babel-traverse\lib\context.js:106:17)
    at TraversalContext.visit (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-core\node_modules\babel-traverse\lib\context.js:193:19)
    at Function.traverse.node (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-core\node_modules\babel-traverse\lib\index.js:139:17)
    at NodePath.visit (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-core\node_modules\babel-traverse\lib\path\context.js:106:22)
    at TraversalContext.visitQueue (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-core\node_modules\babel-traverse\lib\context.js:151:16)
    at TraversalContext.visitSingle (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-core\node_modules\babel-traverse\lib\context.js:111:19)
    at TraversalContext.visit (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-core\node_modules\babel-traverse\lib\context.js:195:19)
    at Function.traverse.node (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-core\node_modules\babel-traverse\lib\index.js:139:17)
    at NodePath.visit (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-core\node_modules\babel-traverse\lib\path\context.js:106:22)
    at TraversalContext.visitQueue (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-core\node_modules\babel-traverse\lib\context.js:151:16)
    at TraversalContext.visitMultiple (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-core\node_modules\babel-traverse\lib\context.js:106:17)
    at TraversalContext.visit (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-core\node_modules\babel-traverse\lib\context.js:193:19)
    at Function.traverse.node (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-core\node_modules\babel-traverse\lib\index.js:139:17)
    at NodePath.visit (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-core\node_modules\babel-traverse\lib\path\context.js:106:22)
    at TraversalContext.visitQueue (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-core\node_modules\babel-traverse\lib\context.js:151:16)
 @ ./src/edit/index.js 61:16-37

ERROR in ./src/edit/input.js
Module build failed: Error: C:/Users/zhou/Desktop/prosemirror/src/edit/input.js: We found a path that isn't a NodePath instance
    at Function.get (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-preset-es2015\node_modules\babel-plugin-transform-es2015-block-scoping\node_modules\babel-traverse\lib\path\index.js:103:13)
    at TraversalContext.create (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-preset-es2015\node_modules\babel-plugin-transform-es2015-block-scoping\node_modules\babel-traverse\lib\context.js:73:30)
    at TraversalContext.visitMultiple (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-preset-es2015\node_modules\babel-plugin-transform-es2015-block-scoping\node_modules\babel-traverse\lib\context.js:102:25)
    at TraversalContext.visit (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-preset-es2015\node_modules\babel-plugin-transform-es2015-block-scoping\node_modules\babel-traverse\lib\context.js:193:19)
    at Function.traverse.node (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-preset-es2015\node_modules\babel-plugin-transform-es2015-block-scoping\node_modules\babel-traverse\lib\index.js:139:17)
    at traverse (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-preset-es2015\node_modules\babel-plugin-transform-es2015-block-scoping\node_modules\babel-traverse\lib\index.js:61:12)
    at Function.traverse.hasType (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-preset-es2015\node_modules\babel-plugin-transform-es2015-block-scoping\node_modules\babel-traverse\lib\index.js:188:3)
    at BlockScoping.wrapClosure (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-preset-es2015\node_modules\babel-plugin-transform-es2015-block-scoping\lib\index.js:491:47)
    at BlockScoping.run (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-preset-es2015\node_modules\babel-plugin-transform-es2015-block-scoping\lib\index.js:383:12)
    at PluginPass.Loop (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-preset-es2015\node_modules\babel-plugin-transform-es2015-block-scoping\lib\index.js:89:36)
    at newFn (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-core\node_modules\babel-traverse\lib\visitors.js:233:27)
    at NodePath._call (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-core\node_modules\babel-traverse\lib\path\context.js:72:18)
    at NodePath.call (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-core\node_modules\babel-traverse\lib\path\context.js:44:17)
    at NodePath.visit (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-core\node_modules\babel-traverse\lib\path\context.js:102:12)
    at TraversalContext.visitQueue (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-core\node_modules\babel-traverse\lib\context.js:151:16)
    at TraversalContext.visitMultiple (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-core\node_modules\babel-traverse\lib\context.js:106:17)
    at TraversalContext.visit (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-core\node_modules\babel-traverse\lib\context.js:193:19)
    at Function.traverse.node (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-core\node_modules\babel-traverse\lib\index.js:139:17)
    at NodePath.visit (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-core\node_modules\babel-traverse\lib\path\context.js:106:22)
    at TraversalContext.visitQueue (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-core\node_modules\babel-traverse\lib\context.js:151:16)
    at TraversalContext.visitSingle (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-core\node_modules\babel-traverse\lib\context.js:111:19)
    at TraversalContext.visit (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-core\node_modules\babel-traverse\lib\context.js:195:19)
    at Function.traverse.node (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-core\node_modules\babel-traverse\lib\index.js:139:17)
    at NodePath.visit (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-core\node_modules\babel-traverse\lib\path\context.js:106:22)
    at TraversalContext.visitQueue (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-core\node_modules\babel-traverse\lib\context.js:151:16)
    at TraversalContext.visitMultiple (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-core\node_modules\babel-traverse\lib\context.js:106:17)
    at TraversalContext.visit (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-core\node_modules\babel-traverse\lib\context.js:193:19)
    at Function.traverse.node (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-core\node_modules\babel-traverse\lib\index.js:139:17)
    at NodePath.visit (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-core\node_modules\babel-traverse\lib\path\context.js:106:22)
    at TraversalContext.visitQueue (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-core\node_modules\babel-traverse\lib\context.js:151:16)
 @ ./src/edit/main.js 32:13-31

ERROR in ./src/transform/ancestor.js
Module build failed: Error: C:/Users/zhou/Desktop/prosemirror/src/transform/ancestor.js: We found a path that isn't a NodePath instance
    at Function.get (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-preset-es2015\node_modules\babel-plugin-transform-es2015-block-scoping\node_modules\babel-traverse\lib\path\index.js:103:13)
    at TraversalContext.create (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-preset-es2015\node_modules\babel-plugin-transform-es2015-block-scoping\node_modules\babel-traverse\lib\context.js:73:30)
    at TraversalContext.visitMultiple (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-preset-es2015\node_modules\babel-plugin-transform-es2015-block-scoping\node_modules\babel-traverse\lib\context.js:102:25)
    at TraversalContext.visit (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-preset-es2015\node_modules\babel-plugin-transform-es2015-block-scoping\node_modules\babel-traverse\lib\context.js:193:19)
    at Function.traverse.node (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-preset-es2015\node_modules\babel-plugin-transform-es2015-block-scoping\node_modules\babel-traverse\lib\index.js:139:17)
    at traverse (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-preset-es2015\node_modules\babel-plugin-transform-es2015-block-scoping\node_modules\babel-traverse\lib\index.js:61:12)
    at Function.traverse.hasType (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-preset-es2015\node_modules\babel-plugin-transform-es2015-block-scoping\node_modules\babel-traverse\lib\index.js:188:3)
    at BlockScoping.wrapClosure (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-preset-es2015\node_modules\babel-plugin-transform-es2015-block-scoping\lib\index.js:491:47)
    at BlockScoping.run (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-preset-es2015\node_modules\babel-plugin-transform-es2015-block-scoping\lib\index.js:383:12)
    at PluginPass.Loop (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-preset-es2015\node_modules\babel-plugin-transform-es2015-block-scoping\lib\index.js:89:36)
    at newFn (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-core\node_modules\babel-traverse\lib\visitors.js:233:27)
    at NodePath._call (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-core\node_modules\babel-traverse\lib\path\context.js:72:18)
    at NodePath.call (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-core\node_modules\babel-traverse\lib\path\context.js:44:17)
    at NodePath.visit (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-core\node_modules\babel-traverse\lib\path\context.js:102:12)
    at TraversalContext.visitQueue (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-core\node_modules\babel-traverse\lib\context.js:151:16)
    at TraversalContext.visitMultiple (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-core\node_modules\babel-traverse\lib\context.js:106:17)
    at TraversalContext.visit (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-core\node_modules\babel-traverse\lib\context.js:193:19)
    at Function.traverse.node (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-core\node_modules\babel-traverse\lib\index.js:139:17)
    at NodePath.visit (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-core\node_modules\babel-traverse\lib\path\context.js:106:22)
    at TraversalContext.visitQueue (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-core\node_modules\babel-traverse\lib\context.js:151:16)
    at TraversalContext.visitSingle (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-core\node_modules\babel-traverse\lib\context.js:111:19)
    at TraversalContext.visit (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-core\node_modules\babel-traverse\lib\context.js:195:19)
    at Function.traverse.node (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-core\node_modules\babel-traverse\lib\index.js:139:17)
    at NodePath.visit (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-core\node_modules\babel-traverse\lib\path\context.js:106:22)
    at TraversalContext.visitQueue (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-core\node_modules\babel-traverse\lib\context.js:151:16)
    at TraversalContext.visitMultiple (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-core\node_modules\babel-traverse\lib\context.js:106:17)
    at TraversalContext.visit (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-core\node_modules\babel-traverse\lib\context.js:193:19)
    at Function.traverse.node (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-core\node_modules\babel-traverse\lib\index.js:139:17)
    at NodePath.visit (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-core\node_modules\babel-traverse\lib\path\context.js:106:22)
    at TraversalContext.visitQueue (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-core\node_modules\babel-traverse\lib\context.js:151:16)
 @ ./src/transform/index.js 32:16-37

ERROR in ./src/transform/replace.js
Module build failed: Error: C:/Users/zhou/Desktop/prosemirror/src/transform/replace.js: We found a path that isn't a NodePath instance
    at Function.get (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-preset-es2015\node_modules\babel-plugin-transform-es2015-block-scoping\node_modules\babel-traverse\lib\path\index.js:103:13)
    at TraversalContext.create (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-preset-es2015\node_modules\babel-plugin-transform-es2015-block-scoping\node_modules\babel-traverse\lib\context.js:73:30)
    at TraversalContext.visitMultiple (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-preset-es2015\node_modules\babel-plugin-transform-es2015-block-scoping\node_modules\babel-traverse\lib\context.js:102:25)
    at TraversalContext.visit (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-preset-es2015\node_modules\babel-plugin-transform-es2015-block-scoping\node_modules\babel-traverse\lib\context.js:193:19)
    at Function.traverse.node (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-preset-es2015\node_modules\babel-plugin-transform-es2015-block-scoping\node_modules\babel-traverse\lib\index.js:139:17)
    at traverse (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-preset-es2015\node_modules\babel-plugin-transform-es2015-block-scoping\node_modules\babel-traverse\lib\index.js:61:12)
    at Function.traverse.hasType (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-preset-es2015\node_modules\babel-plugin-transform-es2015-block-scoping\node_modules\babel-traverse\lib\index.js:188:3)
    at BlockScoping.wrapClosure (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-preset-es2015\node_modules\babel-plugin-transform-es2015-block-scoping\lib\index.js:491:47)
    at BlockScoping.run (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-preset-es2015\node_modules\babel-plugin-transform-es2015-block-scoping\lib\index.js:383:12)
    at PluginPass.BlockStatementProgram (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-preset-es2015\node_modules\babel-plugin-transform-es2015-block-scoping\lib\index.js:96:24)
    at newFn (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-core\node_modules\babel-traverse\lib\visitors.js:233:27)
    at NodePath._call (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-core\node_modules\babel-traverse\lib\path\context.js:72:18)
    at NodePath.call (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-core\node_modules\babel-traverse\lib\path\context.js:44:17)
    at NodePath.visit (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-core\node_modules\babel-traverse\lib\path\context.js:102:12)
    at TraversalContext.visitQueue (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-core\node_modules\babel-traverse\lib\context.js:151:16)
    at TraversalContext.visitSingle (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-core\node_modules\babel-traverse\lib\context.js:111:19)
    at TraversalContext.visit (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-core\node_modules\babel-traverse\lib\context.js:195:19)
    at Function.traverse.node (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-core\node_modules\babel-traverse\lib\index.js:139:17)
    at NodePath.visit (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-core\node_modules\babel-traverse\lib\path\context.js:106:22)
    at TraversalContext.visitQueue (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-core\node_modules\babel-traverse\lib\context.js:151:16)
    at TraversalContext.visitMultiple (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-core\node_modules\babel-traverse\lib\context.js:106:17)
    at TraversalContext.visit (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-core\node_modules\babel-traverse\lib\context.js:193:19)
    at Function.traverse.node (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-core\node_modules\babel-traverse\lib\index.js:139:17)
    at NodePath.visit (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-core\node_modules\babel-traverse\lib\path\context.js:106:22)
    at TraversalContext.visitQueue (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-core\node_modules\babel-traverse\lib\context.js:151:16)
    at TraversalContext.visitSingle (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-core\node_modules\babel-traverse\lib\context.js:111:19)
    at TraversalContext.visit (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-core\node_modules\babel-traverse\lib\context.js:195:19)
    at Function.traverse.node (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-core\node_modules\babel-traverse\lib\index.js:139:17)
    at NodePath.visit (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-core\node_modules\babel-traverse\lib\path\context.js:106:22)
    at TraversalContext.visitQueue (C:\Users\zhou\Desktop\prosemirror\node_modules\babel-core\node_modules\babel-traverse\lib\context.js:151:16)
 @ ./src/transform/index.js 93:0-20

**Comment by CooCooooo** [comment]
// here is my .babelrc
{
  "presets": ["es2015"],
  "plugins": ["transform-runtime"]
}

**Comment by marijnh** [comment]
I've successfully built the project demo with webpack using this configuration file:

```json
module.exports = {
  entry: "./demo.js",
  output: {
    filename: "demo-built.js"
  },
  module: {
    loaders: [
      {
        test: /\.js$/,
        exclude: /node_modules/,
        loader: 'babel'
      }
    ]
  }
}
```

I don't know how a .babelrc file factors into this -- I don't have one.

**Comment by CooCooooo** [comment]
thanks, but I have my system reset, I will test it as soon as I get my workspace down. and I want to konw which version babel you use

**Comment by CooCooooo** [comment]
thanks, but I get my system reset, I will try it as soon as I get my workspace down. I think I get the error probly because I use the babel 6.

**Comment by CooCooooo** [comment]
the problem caused by the babel 6

**Comment by forresto** [comment]
@CooCooooo I'm getting the same issue as you with babel 6. Let me know if you figure it out. Here is how I'm trying to explicitly include it in the webpack config:

```
 ...
  module: {
    loaders: [
      {
        test: /\.js$/, 
        loader: 'babel-loader', 
        include: [
          path.resolve(__dirname, 'demo'),
          path.resolve(__dirname, 'src'),
          path.resolve(__dirname, 'node_modules', 'prosemirror')
        ]
      }
    ]
    ...
```

**Comment by forresto** [comment]
Made a PR. Another fix is to add `query` to the babel-loader config above: 

```
      {
        test: /\.js$/, 
        loader: 'babel-loader', 
        include: [
          path.resolve(__dirname, 'demo'),
          path.resolve(__dirname, 'src'),
          path.resolve(__dirname, 'node_modules', 'prosemirror')
        ],
        query: {
          presets: ['es2015']
        }
      },
```

**Comment by CooCooooo** [comment]
I use the babel list in the package.json, and follow the step in the readme file, it works well. 

Maybe the author will upgrade the dependence to the babel6 sometime
