### ISSUE TITLE
Fresh installation failed with npm 

### ISSUE THREAD

**Issue by johnking** [ProseMirror/prosemirror#673]
Simply follows the steps in [Prosemirror](https://www.npmjs.com/package/prosemirror)
1. `git clone https://github.com/ProseMirror/prosemirror.git`
2. `cd prosemirror`
3. `npm install`

and got errors:
 
```
Cloning into 'website'...
npm ERR! path /Users/johnking/workshop/richEditors/prosemirror/prosemirror/model/node_modules/.staging/orderedmap-6e59bc8f
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename
npm ERR! enoent ENOENT: no such file or directory, rename '/Users/johnking/workshop/richEditors/prosemirror/prosemirror/model/node_modules/.staging/orderedmap-6e59bc8f' -> '/Users
/johnking/workshop/richEditors/prosemirror/prosemirror/model/node_modules/orderedmap'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/johnking/.npm/_logs/2017-07-19T21_23_33_792Z-debug.log

    at checkExecSyncError (child_process.js:481:13)
    at Object.execFileSync (child_process.js:501:13)
    at run (/Users/johnking/workshop/richEditors/prosemirror/prosemirror/bin/pm.js:61:16)
    at modsAndWebsite.forEach.repo (/Users/johnking/workshop/richEditors/prosemirror/prosemirror/bin/pm.js:136:5)

    at Array.forEach (native)
    at clone (/Users/johnking/workshop/richEditors/prosemirror/prosemirror/bin/pm.js:135:18)
    at start (/Users/johnking/workshop/richEditors/prosemirror/prosemirror/bin/pm.js:31:32)
    at Object.<anonymous> (/Users/johnking/workshop/richEditors/prosemirror/prosemirror/bin/pm.js:261:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! prosemirror@0.0.0 install: `bin/pm clone`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the prosemirror@0.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

I am using:
``` 
node: 6.10.2
npm: 5.3.0
```

**Comment by adrianheine** [comment]
This is probably related to npm 5, see for example npm/npm#17444.

**Comment by marijnh** [comment]
Yes, looking through that report, I guess this is a NPM bug, so I'm going to close it here.

**Comment by johnking** [comment]
Thanks for your reply @adrianheine @marijnh
