### ISSUE TITLE
Clean installation running problems

### ISSUE THREAD

**Issue by edirectorios** [ProseMirror/prosemirror#815]
After starting the service wit the npm run demo the server outputs this errors

Any help would be appreciated.
Thanks.

```
> prosemirror@0.0.0 demo /home/tony/prosemirror
> moduleserve demo

Module server listening on localhost:8080
internal/fs/watchers.js:167
    throw error;
    ^

Error: ENOSPC: no space left on device, watch '/home/tony/prosemirror/demo/demo.js'
    at FSWatcher.start (internal/fs/watchers.js:161:26)
    at Object.watch (fs.js:1234:11)
    at ModuleServer.sendScript (/home/tony/prosemirror/node_modules/moduleserve/moduleserver.js:128:21)
    at ModuleServer.handleRequest (/home/tony/prosemirror/node_modules/moduleserve/moduleserver.js:67:10)
    at Server.<anonymous> (/home/tony/prosemirror/node_modules/moduleserve/index.js:35:3)
    at Server.emit (events.js:182:13)
    at parserOnIncoming (_http_server.js:658:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! prosemirror@0.0.0 demo: `moduleserve demo`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the prosemirror@0.0.0 demo script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/tony/.npm/_logs/2018-07-02T15_26_24_854Z-debug.log
```

**Comment by marijnh** [comment]
Sounds like your hard disk is full.

**Comment by edirectorios** [comment]
is not the case :(

**Comment by marijnh** [comment]
Fair enough, but ENOSPC is something coming from the bowels of Node, and usually means full disk, so I don't think this is something that the code in this repository is doing. I'm going to close this until more information pointing at an error in our code is available.

**Comment by edirectorios** [comment]
i must start it with `sudo npm run demo`
This is not mentioned in the wiki
Solved!

**Comment by marijnh** [comment]
> This is not mentioned in the wiki

Because it's not a general problem—on my system it runs fine as a normal user. Which operating system are you on?

**Comment by edirectorios** [comment]
I'm with linux mint .
Hope it helps someone
