### ISSUE TITLE
maybeStep can also fail with an exception

### ISSUE THREAD

**Issue by mitar** [ProseMirror/prosemirror#873]
### Issue details

During rebase on the server I am using `maybeStep` like it is used in collab module, but I am observing that `maybeStep` can also fail with an exception:

```
RangeError: Position 235 out of range
2018-11-23_07:18:19.48518     at Function.resolve (/bundle/programs/server/npm/node_modules/prosemirror-model/dist/index.js:945:55)
2018-11-23_07:18:19.48519     at Function.resolveCached (/bundle/programs/server/npm/node_modules/prosemirror-model/dist/index.js:968:60)
2018-11-23_07:18:19.48519     at Node.resolve (/bundle/programs/server/npm/node_modules/prosemirror-model/dist/index.js:1239:70)
2018-11-23_07:18:19.48520     at Node.replace$1 [as replace] (/bundle/programs/server/npm/node_modules/prosemirror-model/dist/index.js:1194:23)
2018-11-23_07:18:19.48520     at Function.fromReplace (/bundle/programs/server/npm/node_modules/prosemirror-transform/dist/index.js:458:30)
2018-11-23_07:18:19.48521     at ReplaceStep.apply (/bundle/programs/server/npm/node_modules/prosemirror-transform/dist/index.js:482:23)
2018-11-23_07:18:19.48521     at Transform.maybeStep (/bundle/programs/server/npm/node_modules/prosemirror-transform/dist/index.js:345:21)
```

I find this surprising.

### Steps to reproduce

I have not yet been able to come up with the reproduction. I am currently observing this in our logs and investigating.

### ProseMirror version

```
prosemirror-view@1.3.0
prosemirror-model@1.4.3
prosemirror-state@1.2.0
prosemirror-transform@1.0.10
```

**Comment by marijnh** [comment]
Yes, this is by design. The method expects the step to be in the same coordinate space as the document you're trying to apply it to—you can't just try to apply any step to any document. The checks during application are about the structure of the step fitting into the document, not about the positions it refers to being valid for that document. I think you have some other bug where the steps are being mapped incorrectly (or not being mapped when they should be).

**Comment by mitar** [comment]
Thanks for confirming this. I will dig deeper.

**Comment by mitar** [comment]
I found a reproduction: https://github.com/ProseMirror/prosemirror/issues/874
