### ISSUE TITLE
prosemirror-view DOMObserver.stop does not null check `this.observer`

### ISSUE THREAD

**Issue by asaloff** [ProseMirror/prosemirror#949]
### Issue details

When I run my Jest tests I get `TypeError: Cannot read property 'takeRecords' of undefined` because `this.observer` is undefined here https://github.com/ProseMirror/prosemirror-view/blob/master/src/domobserver.js#L52

Error I'm getting:

```
    TypeError: Cannot read property 'takeRecords' of undefined

      at DOMObserver.stop (node_modules/prosemirror-view/src/domobserver.js:51:30)
      at EditorView.updateStateInner (node_modules/prosemirror-view/src/index.js:135:24)
      at EditorView.updateState (node_modules/prosemirror-view/src/index.js:109:10)
      at Editor.setOptions (node_modules/tiptap/dist/tiptap.common.js:1042:19)
      at VueComponent.handler (src/components/notes/NoteEditor.vue:1184:23)
      at VueComponent.Vue.$watch (node_modules/vue/dist/vue.runtime.common.dev.js:4926:12)
      at createWatcher (node_modules/vue/dist/vue.runtime.common.dev.js:4883:13)
      at initWatch (node_modules/vue/dist/vue.runtime.common.dev.js:4865:7)
      at initState (node_modules/vue/dist/vue.runtime.common.dev.js:4628:5)
      at VueComponent.Vue._init (node_modules/vue/dist/vue.runtime.common.dev.js:4981:5)
      at new VueComponent (node_modules/vue/dist/vue.runtime.common.dev.js:5128:12)
      at createComponentInstanceForVnode (node_modules/vue/dist/vue.runtime.common.dev.js:3277:10)
      at init (node_modules/vue/dist/vue.runtime.common.dev.js:3108:45)
      at createComponent (node_modules/vue/dist/vue.runtime.common.dev.js:5952:9)
      at createElm (node_modules/vue/dist/vue.runtime.common.dev.js:5899:9)
      at VueComponent.patch [as __patch__] (node_modules/vue/dist/vue.runtime.common.dev.js:6449:7)
      at VueComponent.Vue._update (node_modules/vue/dist/vue.runtime.common.dev.js:3927:19)
      at VueComponent.updateComponent (node_modules/vue/dist/vue.runtime.common.dev.js:4048:10)
      at Watcher.get (node_modules/vue/dist/vue.runtime.common.dev.js:4459:25)
      at new Watcher (node_modules/vue/dist/vue.runtime.common.dev.js:4448:12)
      at mountComponent (node_modules/vue/dist/vue.runtime.common.dev.js:4055:3)
      at VueComponent.Object.<anonymous>.Vue.$mount (node_modules/vue/dist/vue.runtime.common.dev.js:8386:10)
      at mount (node_modules/@vue/test-utils/dist/vue-test-utils.js:8649:21)
      at shallowMount (node_modules/@vue/test-utils/dist/vue-test-utils.js:8677:10)
      at createShallowWrapper (src/utilities/testFactoryFunctions.js:163:10)
      at Object.<anonymous> (src/components/notes/__tests__/NoteEditor.spec.js:6:21)
```

### Steps to reproduce

I am not sure how to reproduce. I'm getting this error on a very large Vue app in one of the tests that simply mounts the component and takes a snapshot. The issue is really simple though and would just involve doing a null check in the DOMObserver.stop function (`let take = this.observer ? this.observer.takeRecords() : []`). There is a null check a few lines down so I don't think I'm off-base (https://github.com/ProseMirror/prosemirror-view/blob/master/src/domobserver.js#L57).

### ProseMirror version

`prosemirror-view@^1.0.0`

### Affected platforms

- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer
- [x] Other

Happening in JSDOM (run with Jest and vue-test-utils)

**Comment by marijnh** [comment]
You appear to be calling `updateState` on a view that has already been destroyed. This isn't supported—after destroying a view you can't do anything with it anymore.
